In [1]:
import os
import pandas as pd
import numpy as np
import librosa
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import tensorflow as tf

In [2]:
fold9 = [os.path.join('archive', 'fold9', f) for file, _, filename in os.walk(os.path.join(os.getcwd(), 'archive', 'fold9')) for f in filename]
fold8 = [os.path.join('archive', 'fold8', f) for file, _, filename in os.walk(os.path.join(os.getcwd(), 'archive', 'fold8')) for f in filename]
fold7 = [os.path.join('archive', 'fold7', f) for file, _, filename in os.walk(os.path.join(os.getcwd(), 'archive', 'fold7')) for f in filename]
fold6 = [os.path.join('archive', 'fold6', f) for file, _, filename in os.walk(os.path.join(os.getcwd(), 'archive', 'fold6')) for f in filename]
fold5 = [os.path.join('archive', 'fold5', f) for file, _, filename in os.walk(os.path.join(os.getcwd(), 'archive', 'fold5')) for f in filename]
fold4 = [os.path.join('archive', 'fold4', f) for file, _, filename in os.walk(os.path.join(os.getcwd(), 'archive', 'fold4')) for f in filename]
fold3 = [os.path.join('archive', 'fold3', f) for file, _, filename in os.walk(os.path.join(os.getcwd(), 'archive', 'fold3')) for f in filename]
fold2 = [os.path.join('archive', 'fold2', f) for file, _, filename in os.walk(os.path.join(os.getcwd(), 'archive', 'fold2')) for f in filename]
fold1 = [os.path.join('archive', 'fold1', f) for file, _, filename in os.walk(os.path.join(os.getcwd(), 'archive', 'fold1')) for f in filename]
fold10 = [os.path.join('archive', 'fold10', f) for file, _, filename in os.walk(os.path.join(os.getcwd(), 'archive', 'fold10')) for f in filename]

In [3]:
wav_files_list = fold1 + fold2 + fold3 + fold4 + fold5 + fold6 + fold7 + fold8 + fold9 + fold10

In [4]:
df = pd.read_csv('archive/UrbanSound8K.csv')

df

,slice_file_name,fsID,start,end,salience,fold,classID,class
0,100032-3-0-0.wav,100032,0.000000,0.317551,1,5,3,dog_bark
1,100263-2-0-117.wav,100263,58.500000,62.500000,1,5,2,children_playing
2,100263-2-0-121.wav,100263,60.500000,64.500000,1,5,2,children_playing
3,100263-2-0-126.wav,100263,63.000000,67.000000,1,5,2,children_playing
4,100263-2-0-137.wav,100263,68.500000,72.500000,1,5,2,children_playing
...,...,...,...,...,...,...,...,...
8727,99812-1-2-0.wav,99812,159.522205,163.522205,2,7,1,car_horn
8728,99812-1-3-0.wav,99812,181.142431,183.284976,2,7,1,car_horn
8729,99812-1-4-0.wav,99812,242.691902,246.197885,2,7,1,car_horn
8730,99812-1-5-0.wav,99812,253.209850,255.741948,2,7,1,car_horn
8731,99812-1-6-0.wav,99812,332.289233,334.821332,2,7,1,car_horn

In [5]:
in_order = list(df.slice_file_name)

In [6]:
files_in_order = [i for idx, row in df.iterrows() for i in wav_files_list if i.endswith(row.slice_file_name)]

In [7]:
def create_spectrogram(wav_file):
    wav, sample_rate = librosa.load(wav_file)
    stft = librosa.stft(wav)
    spectrogram = np.abs(stft)
    return spectrogram

In [8]:
np.shape(create_spectrogram(files_in_order[0]))

(1025, 14)

In [9]:
indexes_to_remove = []
for idx, i in enumerate(files_in_order):
    if np.shape(create_spectrogram(i)) != (1025, 173):
        indexes_to_remove.append(idx)

/opt/anaconda3/lib/python3.12/site-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=1323
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=1103
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/librosa/core/spectrum.py:266: UserWarning: n_fft=2048 is too large for input signal of length=1523
  warnings.warn(

In [10]:
len(indexes_to_remove)

1405

In [11]:
df = df.drop(indexes_to_remove[:-1])

In [12]:
df

,slice_file_name,fsID,start,end,salience,fold,classID,class
1,100263-2-0-117.wav,100263,58.500000,62.500000,1,5,2,children_playing
2,100263-2-0-121.wav,100263,60.500000,64.500000,1,5,2,children_playing
3,100263-2-0-126.wav,100263,63.000000,67.000000,1,5,2,children_playing
4,100263-2-0-137.wav,100263,68.500000,72.500000,1,5,2,children_playing
5,100263-2-0-143.wav,100263,71.500000,75.500000,1,5,2,children_playing
...,...,...,...,...,...,...,...,...
8724,99812-1-0-1.wav,99812,38.676254,42.676254,2,7,1,car_horn
8725,99812-1-0-2.wav,99812,39.176254,43.176254,2,7,1,car_horn
8726,99812-1-1-0.wav,99812,89.207778,93.207778,2,7,1,car_horn
8727,99812-1-2-0.wav,99812,159.522205,163.522205,2,7,1,car_horn
8728,99812-1-3-0.wav,99812,181.142431,183.284976,2,7,1,car_horn

In [13]:
files_in_order = [i for idx, row in df.iterrows() for i in wav_files_list if i.endswith(row.slice_file_name)]

In [14]:
preprocessed_vids = []
for i in files_in_order:
    preprocessed_vids.append(create_spectrogram(i))

In [15]:
y = df['class']

In [16]:
df

,slice_file_name,fsID,start,end,salience,fold,classID,class
1,100263-2-0-117.wav,100263,58.500000,62.500000,1,5,2,children_playing
2,100263-2-0-121.wav,100263,60.500000,64.500000,1,5,2,children_playing
3,100263-2-0-126.wav,100263,63.000000,67.000000,1,5,2,children_playing
4,100263-2-0-137.wav,100263,68.500000,72.500000,1,5,2,children_playing
5,100263-2-0-143.wav,100263,71.500000,75.500000,1,5,2,children_playing
...,...,...,...,...,...,...,...,...
8724,99812-1-0-1.wav,99812,38.676254,42.676254,2,7,1,car_horn
8725,99812-1-0-2.wav,99812,39.176254,43.176254,2,7,1,car_horn
8726,99812-1-1-0.wav,99812,89.207778,93.207778,2,7,1,car_horn
8727,99812-1-2-0.wav,99812,159.522205,163.522205,2,7,1,car_horn
8728,99812-1-3-0.wav,99812,181.142431,183.284976,2,7,1,car_horn

In [17]:
more_idx_remove = []
for idx, i in enumerate(preprocessed_vids):
    if np.shape(i) != (1025, 173):
        more_idx_remove.append(idx)

In [18]:
df = df.reset_index()

In [19]:
df = df.drop(more_idx_remove)

In [20]:
actual_X_data = []
for idx, i in enumerate(preprocessed_vids):
    if idx not in more_idx_remove:
        actual_X_data.append(i)

In [21]:
len(df)

7214

In [22]:
len(actual_X_data)

7214

In [23]:
X = actual_X_data
y = df['class']

In [24]:
le = LabelEncoder()
y = le.fit_transform(y)

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y)

In [26]:
X_train, X_test, y_train, y_test = np.array(X_train), np.array(X_test), np.array(y_train), np.array(y_test)

In [ ]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Conv2D(32, (3,3), input_shape=(1025, 173, 1), activation='relu'))
model.add(tf.keras.layers.MaxPooling2D(2,2))
model.add(tf.keras.layers.Conv2D(64, (3,3), activation='relu'))
model.add(tf.keras.layers.MaxPooling2D(2,2))
model.add(tf.keras.layers.Conv2D(64, (3,3), activation='relu'))
model.add(tf.keras.layers.MaxPooling2D(2,2))

model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(64, activation='relu'))
model.add(tf.keras.layers.Dense(10, activation='softmax'))

model.compile(optimizer='Adam', metrics=['accuracy'], loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True))

model.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test))

In [ ]:
model.evaluate(X_test, y_test)

In [ ]:
predictions = model.predict(X_test)

In [ ]:
[np.argmax(predictions[i]) for i in range(20)]

In [ ]:
y_test[0:20]